#ifndef KEYWORD_H_
#define KEYWORD_H_

#include "tokens.h"

int parse_keyword(const char *in, int length, enum TokenType);

enum Keyword {
	KEYWORD_NONE = -1,
	KEYWORD_BOOL,
	KEYWORD_BREAK,
	KEYWORD_CASE,
	KEYWORD_CHAR,
	KEYWORD_CONST,
	KEYWORD_CONTINUE,
	KEYWORD_DO,
	KEYWORD_ELSE,
	KEYWORD_ENUM,
	KEYWORD_FALSE,
	KEYWORD_FOR,
	KEYWORD_GOTO,
	KEYWORD_IF,
	KEYWORD_INT,
	KEYWORD_I8,
	KEYWORD_I16,
	KEYWORD_I32,
	KEYWORD_RETURN,
	KEYWORD_SIZEOF,
	KEYWORD_STATIC,
	KEYWORD_STRUCT,
	KEYWORD_SWITCH,
	KEYWORD_TRUE,
	KEYWORD_UNION,
	KEYWORD_U8,
	KEYWORD_U16,
	KEYWORD_U32,
	KEYWORD_VOID,
	KEYWORD_WHILE,

	KEYWORD_COUNT,
};

enum PreProcKeyword {
	PREPROC_NONE = -1,
	PREPROC_ASSERT,
	PREPROC_DEFINE,
	PREPROC_ELIF,
	PREPROC_ELSE,
	PREPROC_EMBED,
	PREPROC_ENDIF,
	PREPROC_ERROR,
	PREPROC_IF,
	PREPROC_INCLUDE,
	PREPROC_PRAGMA,
	PREPROC_WARNING,

	PREPROC_COUNT,
};

#endif //KEYWORD_H_
